baseURL = "https://Tdxxxx-student.github.io/"
languageCode = "zh-cn"
title = "æˆ‘çš„ç©ºé—´"
theme = "PaperMod"
copyright = "tdx0307"
hasCJKLanguage = true

[taxonomies]
  category = "categories"
  tag = "tags"

[pagination]
  pagerSize = 8

[params]
  customCSS = ["css/custom.css"]
  defaultTheme = "auto"
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowShareButtons = false
  ShowReadingTime = true
  ShowToc = true
  TocOpen = true
  TocSide = "right"
  DateFormat = "2006-01-02"

[params.homeInfoParams]
  Title = "ä½ å¥½ï¼Œæˆ‘æ˜¯ Tdxxxx"
  Content = "æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢ä¸»é¡µï¼"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]


[[menu.main]]
  name = "å½’æ¡£"
  url = "/archives/"
  weight = 2

[[menu.main]]
  name = "é¦–é¡µ"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "åˆ†ç±»"
  url = "/categories/"
  weight = 3

[[menu.main]]
  name = "æ ‡ç­¾"
  url = "/tags/"
  weight = 4

[[menu.main]]
  identifier = "search"
  name = "ğŸ” "
  url = "/search/"
  weight = 5