baseURL = "https://Tdxxxx-student.github.io/"
languageCode = "zh-cn"
title = "我的空间"
theme = "PaperMod"
copyright = "tdx0307"
hasCJKLanguage = true

[taxonomies]
  category = "categories"
  tag = "tags"

[pagination]
  pagerSize = 4

[params]
  defaultTheme = "auto"
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowShareButtons = false
  ShowReadingTime = true
  ShowToc = true
  DateFormat = "2006-01-02"

[params.homeInfoParams]
  Title = "你好，我是 Tdxxxx"
  Content = "欢迎来到我的博客主页！"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "分类"
  url = "/categories/"
  weight = 3

[[menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 4